#!/usr/bin/env bash
# gen-index — rebuild docs/adr/README.md from the ADRs themselves.
#
# Eleven ADRs mean eleven scattered Status lines, and a hand-written index rots the first time one
# changes. This reads the real files: the title from the H1, the status from the first bold
# **Status:** value. Run it after editing any ADR.
set -euo pipefail
cd "$(dirname "$0")"
{
  cat <<'HEADER'
# Architecture decisions

Generated by `./gen-index.sh` — edit the ADRs, not this file.

An ADR here is a decision with its evidence attached: what forced it, what was rejected, what
would prove it wrong. Status is written in the ADR itself and says what is actually TRUE, not what
was intended — "PROPOSED" means no code, and a claim only becomes "PROVEN" when something ran.

| # | Decision | Status |
|---|---|---|
HEADER
  for f in 0*.md; do
    num="${f%%-*}"
    title=$(sed -n 's/^# ADR [0-9]* — //p; s/^# ADR [0-9]* - //p' "$f" | head -1)
    [ -n "$title" ] || title=$(sed -n 's/^# //p' "$f" | head -1)
    status=$(grep -m1 -- '- \*\*Status:\*\*' "$f" \
      | sed 's/.*\*\*Status:\*\* *//; s/\*\*//g' \
      | cut -c1-72 | sed 's/[[:space:]]*$//')
    printf '| [%s](%s) | %s | %s |\n' "$num" "$f" "$title" "$status"
  done
  cat <<'FOOTER'

## How they hang together

```
0001 spool + tabId ─────────────► 0009 public protocol ──► 0010 Go client
0002 audio in/out ──────────────►      (media, grants)     (bash retires)
                                            │
0004 site definitions ──► 0005 lifecycle ───┤
     (installed wins)      (login/logout)   ├──► 0011 state export/import
                                            │     (cross-OS sessions)
0006 CLI vs engine ─────────────────────────┘
                                            
0008 Linux build ──► 0003 server + login ──► 0007 releases across OS
     (done)              (unblocked)             (nothing signed yet)
```

**The load-bearing ones to read first:** 0009 (what other people's software may do), 0007 (what a
release is, and why the 109 MB macOS `.app` is not one), and 0011 (why an exported cookie jar is a
credential and not a file).
FOOTER
} > README.md
echo "wrote $(pwd)/README.md"
